[project]
name = "udaan-ai"
version = "1.0.0"
description = "Agentic Platform for Personalized Career & Education Guidance"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pre-commit>=4.3.0",
]
